/**
 * Non-beverage items MGCE packs, lifted from their own MO & Packing List
 * sheets (the 2026 template plus a real filled-in event, merged).
 *
 * These are not inventory: nobody counts how many wood forks are on the shelf.
 * They exist so a pack list line can be picked from a list instead of typed,
 * which is the whole difference between this and a blank Excel cell.
 */
export interface CatalogItem {
  name: string
  /** Where it lives, so the picker can say where to go get it */
  group: string
}

export const CATALOG: CatalogItem[] = [
  { name: "Skinny Wood Taco", group: "Office" },
  { name: "Skinny White Taco", group: "Office" },
  { name: "Wood Rectangle", group: "Office" },
  { name: "Silver Metal Taco", group: "Office" },
  { name: "Black Round Ceramic (select size)", group: "Office" },
  { name: "Skinny Ceramic Oval", group: "Office" },
  { name: "White Tray with Gold Mirror Top", group: "Office" },
  { name: "Black Bento", group: "Office" },
  { name: "White Bento", group: "Office" },
  { name: "White Wide Oval Tray, Grey Rim", group: "Office" },
  { name: "White Ceramic Tray, Gold Rim", group: "Office" },
  { name: "Blue Rectangle Tray, Gold Handles", group: "Office" },
  { name: "White Lucite Rectangle", group: "Office" },
  { name: "Black Lucite Rectangle", group: "Office" },
  { name: "White Lucite Lollipop", group: "Office" },
  { name: "Black Lucite Lollipop", group: "Office" },
  { name: "White Lucite Cone Tray (select size)", group: "Office" },
  { name: "Black Lucite Cone Tray (select size)", group: "Office" },
  { name: "Clear Lucite Cone Tray", group: "Office" },
  { name: "White Resin Bussing", group: "Office" },
  { name: "Black Resin Bussing", group: "Office" },
  { name: "Clear Lucite Shadowbox Tray", group: "Office" },
  { name: "White Cigarette Girl Tray", group: "Office" },
  { name: "Assorted Silver Trays", group: "Office" },
  { name: "Round Silver Beverage Tray", group: "Office" },
  { name: "Wood Taco Tray", group: "Office" },
  { name: "Wood Oval Trays", group: "Office" },
  { name: "Long Rectangular Wood Board", group: "Office" },
  { name: "Wood Paddle Board (pizza)", group: "Office" },
  { name: "Wood Block Board (HexClad)", group: "Office" },
  { name: "White Ceramic Cake Stand (select size)", group: "Office" },
  { name: "White Lace Ceramic Cake Stand (select size)", group: "Office" },
  { name: "White/Gold Stoneware Cake Stand", group: "Office" },
  { name: "Black Ceramic Cake Stand (select size)", group: "Office" },
  { name: "Light Pink Ceramic Cake Stand (select size)", group: "Office" },
  { name: "Light Green Ceramic Cake Stand (select size)", group: "Office" },
  { name: "Wood Cake Stand, assorted", group: "Office" },
  { name: "3-tiered Wood Stand", group: "Office" },
  { name: "Walnut Wood Risers", group: "Office" },
  { name: "Crate Risers", group: "Office" },
  { name: "Vintage Cola Risers", group: "Office" },
  { name: "Silver Hammered Risers, assorted", group: "Office" },
  { name: "Silver Hammered Cubist Risers", group: "Office" },
  { name: "Clear Lucite Risers, assorted", group: "Office" },
  { name: "Black Lucite Risers, assorted", group: "Office" },
  { name: "Black Round Metal Pizza Stand", group: "Office" },
  { name: "Silver Round Orb Bowls, assorted", group: "Office" },
  { name: "Small Wood Bowls, assorted", group: "Office" },
  { name: "Wood Cylinder Bucket", group: "Office" },
  { name: "Square Glass Cubes (select size)", group: "Office" },
  { name: "Long Rectangular Glass Cube", group: "Office" },
  { name: "Glass Candy Jar with Lid (select size)", group: "Office" },
  { name: "Glass Apothecary Jar with Lid (select size)", group: "Office" },
  { name: "Candy Scoop Jar with Metal Lid (select size)", group: "Office" },
  { name: "Staff Meal Plates/Utensils/Napkins", group: "Office" },
  { name: "Staff Meal Serving Spoons/Tongs", group: "Office" },
  { name: "Bar Kit", group: "Office" },
  { name: "Jiggers", group: "Office" },
  { name: "Cutting Board/Knife", group: "Office" },
  { name: "Plastic Measuring Buckets", group: "Office" },
  { name: "Silver Ice Bucket", group: "Office" },
  { name: "Silver Hammered Chill Tub (select size)", group: "Office" },
  { name: "Flared Glass Carafe", group: "Office" },
  { name: "Rounded Glass Carafe", group: "Office" },
  { name: "Glass Drink Dispenser", group: "Office" },
  { name: "Grass Straws", group: "Office" },
  { name: "Acrylic Water Pitchers", group: "Office" },
  { name: "Magnetic Lucite Frames, 8x10", group: "Office" },
  { name: "Magnetic Lucite Frames, 5x7", group: "Office" },
  { name: "Wood/Glass Frame, 8x10", group: "Office" },
  { name: "Dinner Menus", group: "Office" },
  { name: "Placecards", group: "Office" },
  { name: "Food Tent Cards", group: "Office" },
  { name: "Glass Votive Holders, assorted", group: "Office" },
  { name: "Glass Bud Vases, assorted", group: "Office" },
  { name: "Votive Candles", group: "Office" },
  { name: "SLA Permit", group: "Office" },
  { name: "Cocktail Napkins (black/white)", group: "Office" },
  { name: "Paper Towels", group: "Office" },
  { name: "Printed Captains Packet", group: "Office" },
  { name: "Production Kit", group: "Office" },
  { name: "Design Kit", group: "Office" },
  { name: "Black Garbage Bags", group: "Office" },
  { name: "Clear Garbage Bags", group: "Office" },
  { name: "Extension Cords", group: "Office" },
  { name: "Power Strip", group: "Office" },
  { name: "Black Gloves", group: "Office" },
  { name: "Sani Wipes", group: "Office" },
  { name: "Hand Gel", group: "Office" },
  { name: "Small Coffee Maker (12 Cup)", group: "Office" },
  { name: "Medium Coffee Maker (50 Cup)", group: "Office" },
  { name: "Large Coffee Maker (100 Cup)", group: "Office" },
  { name: "Coffee Filters", group: "Office" },
  { name: "Electric Kettle (hot water)", group: "Office" },
  { name: "Pump Pots", group: "Office" },
  { name: "Ceramic Cubes-Sugar/Tea", group: "Office" },
  { name: "Ceramic Cubes-Stirrers/Trash", group: "Office" },
  { name: "Glass Milk Pourers", group: "Office" },
  { name: "Silver Milk Pours", group: "Office" },
  { name: "Wood Stirrers", group: "Office" },
  { name: "Milk/Coffee Signs", group: "Office" },
  { name: "Nespresso Machine", group: "Office" },
  { name: "Nespresso Pods", group: "Office" },
  { name: "Sterno", group: "Office" },
  { name: "Dish Soap and Sponge", group: "Office" },
  { name: "Hammered Tongs - large", group: "Office" },
  { name: "Hammered tongs - small", group: "Office" },
  { name: "MGCE Chef Coat or Apron", group: "Office" },
  { name: "Batch Bucket/Lid", group: "Office" },
  { name: "Mini Black Plastic Pot with Lid (3oz)", group: "Dry Storage" },
  { name: "Round Black Plastic Oval Infinity Pots (3oz)", group: "Dry Storage" },
  { name: "Clear Plastic Square Kova Cups (select size)", group: "Dry Storage" },
  { name: "Clear Plastic Tall Square Kova Cups, 4oz", group: "Dry Storage" },
  { name: "Round Clear Plastic Sphere Cups, 4oz", group: "Dry Storage" },
  { name: "Kraft Boats, 1lb", group: "Dry Storage" },
  { name: "Checkered Boats (select size)", group: "Dry Storage" },
  { name: "Natural Pinewood Boats (select size)", group: "Dry Storage" },
  { name: "Palm Leaf Square Plates (select size)", group: "Dry Storage" },
  { name: "Palm Leaf Round Bowls, 4\"", group: "Dry Storage" },
  { name: "Mini Pizza Boxes (3.5\" sq)", group: "Dry Storage" },
  { name: "Paper Hot Dog Boats (select size)", group: "Dry Storage" },
  { name: "Wood Forks (select size)", group: "Dry Storage" },
  { name: "Wood Spoons (select size)", group: "Dry Storage" },
  { name: "Wood Knives, 6\"", group: "Dry Storage" },
  { name: "Plastic Demi Forks, 4\" (select color)", group: "Dry Storage" },
  { name: "Plastic Demi Spoons, 4\" (select color)", group: "Dry Storage" },
  { name: "Curved Handle Silver Plastic Tasting Spoon, 4\"", group: "Dry Storage" },
  { name: "Bamboo Knotted Cocktail Skewers, 4\"", group: "Dry Storage" },
  { name: "Bamboo Paddle Cocktail Skewers, 6\"", group: "Dry Storage" },
  { name: "Clear Plastic Mini Skewers, 4\"", group: "Dry Storage" },
  { name: "Black Paper Takeout Container (select size)", group: "Dry Storage" },
  { name: "Tossware Plastic Cups, 14oz Vino", group: "Dry Storage" },
  { name: "Tossware Plastic Cups, 4oz Taster", group: "Dry Storage" },
  { name: "Cello Bags", group: "Dry Storage" },
  { name: "White Cups/Lids/Sleeves", group: "Dry Storage" },
  { name: "Sugarcane Drinking Straws", group: "Dry Storage" },
  { name: "MGCE Large Convection Oven", group: "Dry Storage" },
  { name: "Plastic Drink Dispenser", group: "Dry Storage" },
]
